name: Deploy Shiny App to ShinyApps.io

on:
  schedule:
    - cron: '15 9 * * *'  # Runs at 9:15 AM UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("rsconnect", "shiny", "dplyr", "stringr", "tibble", "lubridate", "bslib", "reactable"))
        shell: Rscript {0}

      - name: Build Docker image
        run: docker build -t dashboard_cargas .

      - name: Deploy to shinyapps.io
        run: |
          docker run \
            -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} \
            -e TOKEN=${{ secrets.TOKEN }} \
            -e SECRET=${{ secrets.SECRET }} \
            dashboard_cargas